name: VesperNJ
favicon: null
layout_spectrum: 0.8002
typography_spectrum: 0.0213888599537313
title: Site of the Vesper Football Club over 40
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f8f4f1'
    - '#823114'
    - '#b98756'
    - '#950004'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
