name: VesperNJ
favicon: null
layout_spectrum: 0.3880532484035939
typography_spectrum: 0.0213888599537313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
