name: VesperNJ
favicon: null
layout_spectrum: 0.8002
typography_spectrum: 0.0213888599537313
title: Site of the Vesper Football Club over 40
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#166ea0'
    - '#3c85b0'
    - '#cccfa0'
    - '#699eac'
    - '#9fb29f'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
